### ISSUE TITLE
Bug when game XP is greater than 250,000

### ISSUE THREAD

**Issue by xadamxk** [OMGWTFISTHIS/Medal-of-Honor-Tracker#2]
Example profile: https://hackforums.net/gamecp.php?action=profile&uid=1839849#lgv

Suggested solution: If the user's XP is greater or equal to 250k, cap the progress bar at 100%

**Comment by OMGWTFISTHIS** [comment]
Pushed 1.0.4: The progress bar now utilizes the wholePercent variable, rather than being separately calculated. Thank you!
